/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as common from "./common";
export type { common };
import type * as oracle from "./oracle";
export type { oracle };
