/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDisputeResolver } from "./IDisputeResolver";
export type { IERC721Rent } from "./IERC721Rent";
