/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDisputeResolver,
  IDisputeResolverInterface,
} from "../../../contracts/Interfaces.sol/IDisputeResolver";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "callDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "checkDispute",
    outputs: [
      {
        internalType: "bool",
        name: "rentIsValid",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDisputeResolver__factory {
  static readonly abi = _abi;
  static createInterface(): IDisputeResolverInterface {
    return new utils.Interface(_abi) as IDisputeResolverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDisputeResolver {
    return new Contract(address, _abi, signerOrProvider) as IDisputeResolver;
  }
}
