name: Upload

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
      - run: |
           cp -r contracts/typechain-types frontend/src
           cd frontend
           npm install
           npm build
        
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./frontend/build/ s3://nftip.mirror-ai.com --delete